using Cortex.Mediator.SourceGenerator.Diagnostics;
using Cortex.Mediator.SourceGenerator.Discovery;
using Cortex.Mediator.SourceGenerator.Emitters;
using Cortex.Mediator.SourceGenerator.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Threading;

namespace Cortex.Mediator.SourceGenerator
{
    [Generator(LanguageNames.CSharp)]
    public sealed class CortexMediatorGenerator : IIncrementalGenerator
    {
        private const string AttributeFullName = "Cortex.Mediator.SourceGeneration.CortexMediatorGenerationAttribute";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Step 1: Emit the marker attribute so consumers only need the NuGet package
            context.RegisterPostInitializationOutput(static ctx =>
            {
                ctx.AddSource("CortexMediatorGenerationAttribute.g.cs", @"// <auto-generated/>
namespace Cortex.Mediator.SourceGeneration
{
    /// <summary>
    /// Apply this attribute at assembly level to enable the Cortex Mediator source generator.
    /// </summary>
    [System.AttributeUsage(System.AttributeTargets.Assembly, AllowMultiple = false)]
    internal sealed class CortexMediatorGenerationAttribute : System.Attribute
    {
    }
}
");
            });

            // Step 2: Check if the assembly attribute is present (opt-in gate)
            var hasAttribute = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    AttributeFullName,
                    predicate: static (node, _) => node is CompilationUnitSyntax,
                    transform: static (ctx, _) => true)
                .Collect()
                .Select(static (items, _) => items.Length > 0);

            // Step 3: Discover handlers from class declarations
            var handlerRegistrations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => node is ClassDeclarationSyntax cds && cds.BaseList != null,
                    transform: static (ctx, ct) => GetHandlerRegistrations(ctx, ct))
                .Where(static r => !r.IsEmpty)
                .SelectMany(static (r, _) => r);

            var collectedHandlers = handlerRegistrations.Collect();

            // Step 4: Discover message types for diagnostics
            var messageRegistrations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => node is ClassDeclarationSyntax cds && cds.BaseList != null,
                    transform: static (ctx, ct) => GetMessageRegistrations(ctx, ct))
                .Where(static r => !r.IsEmpty)
                .SelectMany(static (r, _) => r);

            var collectedMessages = messageRegistrations.Collect();

            // Step 5: Combine everything and generate
            var combined = collectedHandlers.Combine(collectedMessages).Combine(hasAttribute);

            context.RegisterSourceOutput(combined, static (spc, input) =>
            {
                var ((handlers, messages), isEnabled) = input;

                if (!isEnabled)
                    return;

                // Report diagnostics
                ReportDiagnostics(spc, handlers, messages);

                // Emit GeneratedMediator
                var mediatorSource = GeneratedMediatorEmitter.Emit(handlers);
                spc.AddSource("GeneratedMediator.g.cs", mediatorSource);

                // Emit GeneratedServiceCollectionExtensions
                var diSource = GeneratedDIEmitter.Emit(handlers);
                spc.AddSource("GeneratedServiceCollectionExtensions.g.cs", diSource);
            });
        }

        private static ImmutableArray<HandlerRegistration> GetHandlerRegistrations(
            GeneratorSyntaxContext context,
            CancellationToken cancellationToken)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;
            var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration, cancellationToken);

            if (symbol is not INamedTypeSymbol namedType)
                return ImmutableArray<HandlerRegistration>.Empty;

            return HandlerDiscovery.FindHandlers(namedType);
        }

        private static ImmutableArray<MessageRegistration> GetMessageRegistrations(
            GeneratorSyntaxContext context,
            CancellationToken cancellationToken)
        {
            var classDeclaration = (ClassDeclarationSyntax)context.Node;
            var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration, cancellationToken);

            if (symbol is not INamedTypeSymbol namedType)
                return ImmutableArray<MessageRegistration>.Empty;

            return MessageDiscovery.FindMessages(namedType);
        }

        private static void ReportDiagnostics(
            SourceProductionContext spc,
            ImmutableArray<HandlerRegistration> handlers,
            ImmutableArray<MessageRegistration> messages)
        {
            var handledCommands = new HashSet<string>(
                handlers.Where(h => h.Kind == InterfaceKind.ReturningCommand)
                    .Select(h => h.MessageFullyQualifiedName));

            var handledVoidCommands = new HashSet<string>(
                handlers.Where(h => h.Kind == InterfaceKind.VoidCommand)
                    .Select(h => h.MessageFullyQualifiedName));

            var handledQueries = new HashSet<string>(
                handlers.Where(h => h.Kind == InterfaceKind.Query)
                    .Select(h => h.MessageFullyQualifiedName));

            var handledStreamQueries = new HashSet<string>(
                handlers.Where(h => h.Kind == InterfaceKind.StreamQuery)
                    .Select(h => h.MessageFullyQualifiedName));

            var handledNotifications = new HashSet<string>(
                handlers.Where(h => h.Kind == InterfaceKind.Notification)
                    .Select(h => h.MessageFullyQualifiedName));

            // Check for unhandled messages
            foreach (var msg in messages)
            {
                switch (msg.Kind)
                {
                    case InterfaceKind.ReturningCommand:
                        if (!handledCommands.Contains(msg.MessageFullyQualifiedName))
                        {
                            spc.ReportDiagnostic(Diagnostic.Create(
                                DiagnosticDescriptors.CommandHasNoHandler,
                                msg.Location,
                                msg.MessageFullyQualifiedName));
                        }
                        break;

                    case InterfaceKind.VoidCommand:
                        if (!handledVoidCommands.Contains(msg.MessageFullyQualifiedName))
                        {
                            spc.ReportDiagnostic(Diagnostic.Create(
                                DiagnosticDescriptors.CommandHasNoHandler,
                                msg.Location,
                                msg.MessageFullyQualifiedName));
                        }
                        break;

                    case InterfaceKind.Query:
                        if (!handledQueries.Contains(msg.MessageFullyQualifiedName))
                        {
                            spc.ReportDiagnostic(Diagnostic.Create(
                                DiagnosticDescriptors.QueryHasNoHandler,
                                msg.Location,
                                msg.MessageFullyQualifiedName));
                        }
                        break;

                    case InterfaceKind.StreamQuery:
                        if (!handledStreamQueries.Contains(msg.MessageFullyQualifiedName))
                        {
                            spc.ReportDiagnostic(Diagnostic.Create(
                                DiagnosticDescriptors.StreamQueryHasNoHandler,
                                msg.Location,
                                msg.MessageFullyQualifiedName));
                        }
                        break;

                    case InterfaceKind.Notification:
                        if (!handledNotifications.Contains(msg.MessageFullyQualifiedName))
                        {
                            spc.ReportDiagnostic(Diagnostic.Create(
                                DiagnosticDescriptors.NotificationHasNoHandler,
                                msg.Location,
                                msg.MessageFullyQualifiedName));
                        }
                        break;
                }
            }

            // Check for duplicate command handlers
            var commandHandlerGroups = handlers
                .Where(h => h.Kind == InterfaceKind.ReturningCommand)
                .GroupBy(h => h.MessageFullyQualifiedName)
                .Where(g => g.Count() > 1);

            foreach (var group in commandHandlerGroups)
            {
                var handlerNames = string.Join(", ", group.Select(h => h.HandlerFullyQualifiedName));
                spc.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.MultipleHandlersForCommand,
                    Location.None,
                    group.Key,
                    handlerNames));
            }

            // Check for duplicate void command handlers
            var voidCommandHandlerGroups = handlers
                .Where(h => h.Kind == InterfaceKind.VoidCommand)
                .GroupBy(h => h.MessageFullyQualifiedName)
                .Where(g => g.Count() > 1);

            foreach (var group in voidCommandHandlerGroups)
            {
                var handlerNames = string.Join(", ", group.Select(h => h.HandlerFullyQualifiedName));
                spc.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.MultipleHandlersForCommand,
                    Location.None,
                    group.Key,
                    handlerNames));
            }

            // Check for duplicate query handlers
            var queryHandlerGroups = handlers
                .Where(h => h.Kind == InterfaceKind.Query)
                .GroupBy(h => h.MessageFullyQualifiedName)
                .Where(g => g.Count() > 1);

            foreach (var group in queryHandlerGroups)
            {
                var handlerNames = string.Join(", ", group.Select(h => h.HandlerFullyQualifiedName));
                spc.ReportDiagnostic(Diagnostic.Create(
                    DiagnosticDescriptors.MultipleHandlersForQuery,
                    Location.None,
                    group.Key,
                    handlerNames));
            }
        }
    }
}
