using Cortex.Mediator.SourceGenerator.Models;
using System.Collections.Immutable;
using System.Linq;

namespace Cortex.Mediator.SourceGenerator.Emitters
{
    internal static class GeneratedDIEmitter
    {
        public static string Emit(ImmutableArray<HandlerRegistration> handlers)
        {
            var sb = new SourceTextBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using Cortex.Mediator;");
            sb.AppendLine("using Cortex.Mediator.DependencyInjection;");
            sb.AppendLine("using Cortex.Mediator.Notifications;");
            sb.AppendLine("using Cortex.Mediator.SourceGeneration;");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine("using System;");
            sb.AppendLine();
            sb.AppendLine("namespace Cortex.Mediator.SourceGeneration");
            sb.OpenBrace();

            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Source-generated DI registration that avoids assembly scanning.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine("[System.CodeDom.Compiler.GeneratedCodeAttribute(\"Cortex.Mediator.SourceGenerator\", \"1.0.0\")]");
            sb.AppendLine("internal static class GeneratedServiceCollectionExtensions");
            sb.OpenBrace();

            sb.AppendLine("public static IServiceCollection AddCortexGeneratedMediator(");
            sb.AppendLine("    this IServiceCollection services,");
            sb.AppendLine("    Action<MediatorOptions>? configure = null)");
            sb.OpenBrace();

            sb.AppendLine("var options = new MediatorOptions();");
            sb.AppendLine("configure?.Invoke(options);");
            sb.AppendLine();

            sb.AppendLine("// Register the generated mediator");
            sb.AppendLine("services.AddScoped<IMediator, GeneratedMediator>();");
            sb.AppendLine();

            sb.AppendLine("// Register notification publish strategy");
            sb.AppendLine("services.AddSingleton(typeof(INotificationPublishStrategy), options.NotificationPublishStrategyType);");
            sb.AppendLine();

            // Group handlers by kind for readability
            var handlerKinds = new[]
            {
                InterfaceKind.ReturningCommand,
                InterfaceKind.VoidCommand,
                InterfaceKind.Query,
                InterfaceKind.StreamQuery,
                InterfaceKind.Notification,
            };

            var processorKinds = new[]
            {
                InterfaceKind.PreProcessor,
                InterfaceKind.PostProcessorWithResponse,
                InterfaceKind.PostProcessorVoid,
            };

            // Emit handler registrations
            var handlerRegs = handlers.Where(h => handlerKinds.Contains(h.Kind)).ToArray();
            if (handlerRegs.Length > 0)
            {
                sb.AppendLine("// Handler registrations");
                foreach (var reg in handlerRegs)
                {
                    sb.AppendLine($"services.Add(new ServiceDescriptor(typeof({reg.ServiceInterfaceFullyQualifiedName}), typeof({reg.HandlerFullyQualifiedName}), ServiceLifetime.Scoped));");
                }
                sb.AppendLine();
            }

            // Emit processor registrations
            var processorRegs = handlers.Where(h => processorKinds.Contains(h.Kind)).ToArray();
            if (processorRegs.Length > 0)
            {
                sb.AppendLine("// Processor registrations");
                foreach (var reg in processorRegs)
                {
                    sb.AppendLine($"services.Add(new ServiceDescriptor(typeof({reg.ServiceInterfaceFullyQualifiedName}), typeof({reg.HandlerFullyQualifiedName}), ServiceLifetime.Transient));");
                }
                sb.AppendLine();
            }

            sb.AppendLine("// Register pipeline behaviors (runtime-configured, cannot be generated)");
            sb.AppendLine("ServiceCollectionExtensions.RegisterPipelineBehaviors(services, options);");
            sb.AppendLine();
            sb.AppendLine("return services;");

            sb.CloseBrace(); // method

            sb.CloseBrace(); // class
            sb.CloseBrace(); // namespace

            return sb.ToString();
        }
    }
}
