using Cortex.Mediator.SourceGenerator.Models;
using System.Collections.Immutable;
using System.Linq;

namespace Cortex.Mediator.SourceGenerator.Emitters
{
    internal static class GeneratedMediatorEmitter
    {
        public static string Emit(ImmutableArray<HandlerRegistration> handlers)
        {
            var returningCommands = handlers
                .Where(h => h.Kind == InterfaceKind.ReturningCommand)
                .ToArray();

            var voidCommands = handlers
                .Where(h => h.Kind == InterfaceKind.VoidCommand)
                .ToArray();

            var queries = handlers
                .Where(h => h.Kind == InterfaceKind.Query)
                .ToArray();

            var streamQueries = handlers
                .Where(h => h.Kind == InterfaceKind.StreamQuery)
                .ToArray();

            var notifications = handlers
                .Where(h => h.Kind == InterfaceKind.Notification)
                .ToArray();

            var sb = new SourceTextBuilder();

            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine();
            sb.AppendLine("using Cortex.Mediator;");
            sb.AppendLine("using Cortex.Mediator.Commands;");
            sb.AppendLine("using Cortex.Mediator.Notifications;");
            sb.AppendLine("using Cortex.Mediator.Queries;");
            sb.AppendLine("using Cortex.Mediator.Streaming;");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using System.Threading;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine();
            sb.AppendLine("namespace Cortex.Mediator.SourceGeneration");
            sb.OpenBrace();

            sb.AppendLine("/// <summary>");
            sb.AppendLine("/// Source-generated mediator that uses compile-time dispatch instead of runtime reflection.");
            sb.AppendLine("/// </summary>");
            sb.AppendLine("[System.CodeDom.Compiler.GeneratedCodeAttribute(\"Cortex.Mediator.SourceGenerator\", \"1.0.0\")]");
            sb.AppendLine("internal sealed class GeneratedMediator : IMediator");
            sb.OpenBrace();

            sb.AppendLine("private readonly IServiceProvider _serviceProvider;");
            sb.AppendLine();
            sb.AppendLine("public GeneratedMediator(IServiceProvider serviceProvider)");
            sb.OpenBrace();
            sb.AppendLine("_serviceProvider = serviceProvider;");
            sb.CloseBrace();

            // SendCommandAsync<TCommand, TResult> - strongly typed (no reflection needed)
            sb.AppendLine();
            EmitStronglyTypedSendCommandReturning(sb);

            // SendCommandAsync<TResult>(ICommand<TResult>) - switch dispatch
            sb.AppendLine();
            EmitSwitchSendCommandReturning(sb, returningCommands);

            // SendCommandAsync<TCommand>(TCommand) - strongly typed (no reflection needed)
            sb.AppendLine();
            EmitStronglyTypedSendCommandVoid(sb);

            // SendCommandAsync(ICommand) - switch dispatch
            sb.AppendLine();
            EmitSwitchSendCommandVoid(sb, voidCommands);

            // SendQueryAsync<TQuery, TResult> - strongly typed
            sb.AppendLine();
            EmitStronglyTypedSendQuery(sb);

            // SendQueryAsync<TResult>(IQuery<TResult>) - switch dispatch
            sb.AppendLine();
            EmitSwitchSendQuery(sb, queries);

            // PublishAsync<TNotification> - strongly typed
            sb.AppendLine();
            EmitStronglyTypedPublish(sb);

            // PublishAsync(INotification) - switch dispatch
            sb.AppendLine();
            EmitSwitchPublish(sb, notifications);

            // CreateStream<TQuery, TResult> - strongly typed
            sb.AppendLine();
            EmitStronglyTypedCreateStream(sb);

            // CreateStream<TResult>(IStreamQuery<TResult>) - switch dispatch
            sb.AppendLine();
            EmitSwitchCreateStream(sb, streamQueries);

            // Pipeline wrapper classes
            sb.AppendLine();
            EmitPipelineWrapperClasses(sb);

            sb.CloseBrace(); // class
            sb.CloseBrace(); // namespace

            return sb.ToString();
        }

        private static void EmitStronglyTypedSendCommandReturning(SourceTextBuilder sb)
        {
            sb.AppendLine("public async Task<TResult> SendCommandAsync<TCommand, TResult>(TCommand command, CancellationToken cancellationToken = default)");
            sb.AppendLine("    where TCommand : ICommand<TResult>");
            sb.OpenBrace();
            sb.AppendLine("var handler = _serviceProvider.GetRequiredService<ICommandHandler<TCommand, TResult>>();");
            sb.AppendLine();
            sb.AppendLine("foreach (var behavior in _serviceProvider.GetServices<ICommandPipelineBehavior<TCommand, TResult>>().Reverse())");
            sb.OpenBrace();
            sb.AppendLine("handler = new PipelineBehaviorNextDelegate<TCommand, TResult>(behavior, handler);");
            sb.CloseBrace();
            sb.AppendLine();
            sb.AppendLine("return await handler.Handle(command, cancellationToken);");
            sb.CloseBrace();
        }

        private static void EmitSwitchSendCommandReturning(SourceTextBuilder sb, HandlerRegistration[] registrations)
        {
            sb.AppendLine("public Task<TResult> SendCommandAsync<TResult>(ICommand<TResult> command, CancellationToken cancellationToken = default)");
            sb.OpenBrace();
            sb.AppendLine("if (command == null) throw new ArgumentNullException(nameof(command));");
            sb.AppendLine();

            if (registrations.Length > 0)
            {
                sb.AppendLine("switch (command)");
                sb.OpenBrace();
                foreach (var reg in registrations)
                {
                    sb.AppendLine($"case {reg.MessageFullyQualifiedName} typed:");
                    sb.Indent();
                    sb.AppendLine($"return (Task<TResult>)(object)SendCommandAsync<{reg.MessageFullyQualifiedName}, {reg.ResultFullyQualifiedName}>(typed, cancellationToken);");
                    sb.Unindent();
                }
                sb.AppendLine("default:");
                sb.Indent();
                sb.AppendLine("throw new InvalidOperationException($\"No handler registered for command type {command.GetType().FullName}. Ensure the handler is in the same compilation where [assembly: CortexMediatorGeneration] is applied.\");");
                sb.Unindent();
                sb.CloseBrace();
            }
            else
            {
                sb.AppendLine("throw new InvalidOperationException($\"No handler registered for command type {command.GetType().FullName}. Ensure the handler is in the same compilation where [assembly: CortexMediatorGeneration] is applied.\");");
            }

            sb.CloseBrace();
        }

        private static void EmitStronglyTypedSendCommandVoid(SourceTextBuilder sb)
        {
            sb.AppendLine("public async Task SendCommandAsync<TCommand>(TCommand command, CancellationToken cancellationToken = default)");
            sb.AppendLine("    where TCommand : ICommand");
            sb.OpenBrace();
            sb.AppendLine("var handler = _serviceProvider.GetRequiredService<ICommandHandler<TCommand>>();");
            sb.AppendLine();
            sb.AppendLine("foreach (var behavior in _serviceProvider.GetServices<ICommandPipelineBehavior<TCommand>>().Reverse())");
            sb.OpenBrace();
            sb.AppendLine("handler = new VoidPipelineBehaviorNextDelegate<TCommand>(behavior, handler);");
            sb.CloseBrace();
            sb.AppendLine();
            sb.AppendLine("await handler.Handle(command, cancellationToken);");
            sb.CloseBrace();
        }

        private static void EmitSwitchSendCommandVoid(SourceTextBuilder sb, HandlerRegistration[] registrations)
        {
            sb.AppendLine("public Task SendCommandAsync(ICommand command, CancellationToken cancellationToken = default)");
            sb.OpenBrace();
            sb.AppendLine("if (command == null) throw new ArgumentNullException(nameof(command));");
            sb.AppendLine();

            if (registrations.Length > 0)
            {
                sb.AppendLine("switch (command)");
                sb.OpenBrace();
                foreach (var reg in registrations)
                {
                    sb.AppendLine($"case {reg.MessageFullyQualifiedName} typed:");
                    sb.Indent();
                    sb.AppendLine($"return SendCommandAsync<{reg.MessageFullyQualifiedName}>(typed, cancellationToken);");
                    sb.Unindent();
                }
                sb.AppendLine("default:");
                sb.Indent();
                sb.AppendLine("throw new InvalidOperationException($\"No handler registered for command type {command.GetType().FullName}. Ensure the handler is in the same compilation where [assembly: CortexMediatorGeneration] is applied.\");");
                sb.Unindent();
                sb.CloseBrace();
            }
            else
            {
                sb.AppendLine("throw new InvalidOperationException($\"No handler registered for command type {command.GetType().FullName}. Ensure the handler is in the same compilation where [assembly: CortexMediatorGeneration] is applied.\");");
            }

            sb.CloseBrace();
        }

        private static void EmitStronglyTypedSendQuery(SourceTextBuilder sb)
        {
            sb.AppendLine("public async Task<TResult> SendQueryAsync<TQuery, TResult>(TQuery query, CancellationToken cancellationToken = default)");
            sb.AppendLine("    where TQuery : IQuery<TResult>");
            sb.OpenBrace();
            sb.AppendLine("var handler = _serviceProvider.GetRequiredService<IQueryHandler<TQuery, TResult>>();");
            sb.AppendLine();
            sb.AppendLine("foreach (var behavior in _serviceProvider.GetServices<IQueryPipelineBehavior<TQuery, TResult>>().Reverse())");
            sb.OpenBrace();
            sb.AppendLine("handler = new QueryPipelineBehaviorNextDelegate<TQuery, TResult>(behavior, handler);");
            sb.CloseBrace();
            sb.AppendLine();
            sb.AppendLine("return await handler.Handle(query, cancellationToken);");
            sb.CloseBrace();
        }

        private static void EmitSwitchSendQuery(SourceTextBuilder sb, HandlerRegistration[] registrations)
        {
            sb.AppendLine("public Task<TResult> SendQueryAsync<TResult>(IQuery<TResult> query, CancellationToken cancellationToken = default)");
            sb.OpenBrace();
            sb.AppendLine("if (query == null) throw new ArgumentNullException(nameof(query));");
            sb.AppendLine();

            if (registrations.Length > 0)
            {
                sb.AppendLine("switch (query)");
                sb.OpenBrace();
                foreach (var reg in registrations)
                {
                    sb.AppendLine($"case {reg.MessageFullyQualifiedName} typed:");
                    sb.Indent();
                    sb.AppendLine($"return (Task<TResult>)(object)SendQueryAsync<{reg.MessageFullyQualifiedName}, {reg.ResultFullyQualifiedName}>(typed, cancellationToken);");
                    sb.Unindent();
                }
                sb.AppendLine("default:");
                sb.Indent();
                sb.AppendLine("throw new InvalidOperationException($\"No handler registered for query type {query.GetType().FullName}. Ensure the handler is in the same compilation where [assembly: CortexMediatorGeneration] is applied.\");");
                sb.Unindent();
                sb.CloseBrace();
            }
            else
            {
                sb.AppendLine("throw new InvalidOperationException($\"No handler registered for query type {query.GetType().FullName}. Ensure the handler is in the same compilation where [assembly: CortexMediatorGeneration] is applied.\");");
            }

            sb.CloseBrace();
        }

        private static void EmitStronglyTypedPublish(SourceTextBuilder sb)
        {
            sb.AppendLine("public async Task PublishAsync<TNotification>(TNotification notification, CancellationToken cancellationToken = default)");
            sb.AppendLine("    where TNotification : INotification");
            sb.OpenBrace();
            sb.AppendLine("var handlers = _serviceProvider.GetServices<INotificationHandler<TNotification>>();");
            sb.AppendLine("var behaviors = _serviceProvider.GetServices<INotificationPipelineBehavior<TNotification>>();");
            sb.AppendLine();
            sb.AppendLine("var behaviorList = behaviors as INotificationPipelineBehavior<TNotification>[] ?? behaviors.ToArray();");
            sb.AppendLine("Array.Reverse(behaviorList);");
            sb.AppendLine();
            sb.AppendLine("var handlerList = handlers as INotificationHandler<TNotification>[] ?? handlers.ToArray();");
            sb.AppendLine("if (handlerList.Length == 0) return;");
            sb.AppendLine();
            sb.AppendLine("var handlerDelegates = new Func<Task>[handlerList.Length];");
            sb.AppendLine("for (int i = 0; i < handlerList.Length; i++)");
            sb.OpenBrace();
            sb.AppendLine("var handler = handlerList[i];");
            sb.AppendLine("NotificationHandlerDelegate handlerDelegate = () => handler.Handle(notification, cancellationToken);");
            sb.AppendLine();
            sb.AppendLine("foreach (var behavior in behaviorList)");
            sb.OpenBrace();
            sb.AppendLine("var currentDelegate = handlerDelegate;");
            sb.AppendLine("var currentBehavior = behavior;");
            sb.AppendLine("handlerDelegate = () => currentBehavior.Handle(notification, currentDelegate, cancellationToken);");
            sb.CloseBrace();
            sb.AppendLine();
            sb.AppendLine("var finalDelegate = handlerDelegate;");
            sb.AppendLine("handlerDelegates[i] = () => finalDelegate();");
            sb.CloseBrace();
            sb.AppendLine();
            sb.AppendLine("var strategy = _serviceProvider.GetService<INotificationPublishStrategy>();");
            sb.AppendLine("if (strategy != null)");
            sb.OpenBrace();
            sb.AppendLine("await strategy.PublishAsync(handlerDelegates, cancellationToken);");
            sb.CloseBrace();
            sb.AppendLine("else");
            sb.OpenBrace();
            sb.AppendLine("await Task.WhenAll(handlerDelegates.Select(d => d()));");
            sb.CloseBrace();
            sb.CloseBrace();
        }

        private static void EmitSwitchPublish(SourceTextBuilder sb, HandlerRegistration[] registrations)
        {
            sb.AppendLine("public Task PublishAsync(INotification notification, CancellationToken cancellationToken = default)");
            sb.OpenBrace();
            sb.AppendLine("if (notification == null) throw new ArgumentNullException(nameof(notification));");
            sb.AppendLine();

            if (registrations.Length > 0)
            {
                sb.AppendLine("switch (notification)");
                sb.OpenBrace();
                // Deduplicate notification types (multiple handlers for same notification)
                var distinctNotifications = registrations
                    .Select(r => r.MessageFullyQualifiedName)
                    .Distinct()
                    .ToArray();
                foreach (var msgFqn in distinctNotifications)
                {
                    sb.AppendLine($"case {msgFqn} typed:");
                    sb.Indent();
                    sb.AppendLine($"return PublishAsync<{msgFqn}>(typed, cancellationToken);");
                    sb.Unindent();
                }
                sb.AppendLine("default:");
                sb.Indent();
                sb.AppendLine("throw new InvalidOperationException($\"No handler registered for notification type {notification.GetType().FullName}. Ensure the handler is in the same compilation where [assembly: CortexMediatorGeneration] is applied.\");");
                sb.Unindent();
                sb.CloseBrace();
            }
            else
            {
                sb.AppendLine("throw new InvalidOperationException($\"No handler registered for notification type {notification.GetType().FullName}. Ensure the handler is in the same compilation where [assembly: CortexMediatorGeneration] is applied.\");");
            }

            sb.CloseBrace();
        }

        private static void EmitStronglyTypedCreateStream(SourceTextBuilder sb)
        {
            sb.AppendLine("public IAsyncEnumerable<TResult> CreateStream<TQuery, TResult>(TQuery query, CancellationToken cancellationToken = default)");
            sb.AppendLine("    where TQuery : IStreamQuery<TResult>");
            sb.OpenBrace();
            sb.AppendLine("if (query == null) throw new ArgumentNullException(nameof(query));");
            sb.AppendLine();
            sb.AppendLine("var handler = _serviceProvider.GetRequiredService<IStreamQueryHandler<TQuery, TResult>>();");
            sb.AppendLine("var behaviors = _serviceProvider.GetServices<IStreamQueryPipelineBehavior<TQuery, TResult>>();");
            sb.AppendLine();
            sb.AppendLine("StreamQueryHandlerDelegate<TResult> handlerDelegate = () => handler.Handle(query, cancellationToken);");
            sb.AppendLine();
            sb.AppendLine("var behaviorArray = behaviors as IStreamQueryPipelineBehavior<TQuery, TResult>[] ?? behaviors.ToArray();");
            sb.AppendLine("for (int i = behaviorArray.Length - 1; i >= 0; i--)");
            sb.OpenBrace();
            sb.AppendLine("var currentDelegate = handlerDelegate;");
            sb.AppendLine("var currentBehavior = behaviorArray[i];");
            sb.AppendLine("handlerDelegate = () => currentBehavior.Handle(query, currentDelegate, cancellationToken);");
            sb.CloseBrace();
            sb.AppendLine();
            sb.AppendLine("return handlerDelegate();");
            sb.CloseBrace();
        }

        private static void EmitSwitchCreateStream(SourceTextBuilder sb, HandlerRegistration[] registrations)
        {
            sb.AppendLine("public IAsyncEnumerable<TResult> CreateStream<TResult>(IStreamQuery<TResult> query, CancellationToken cancellationToken = default)");
            sb.OpenBrace();
            sb.AppendLine("if (query == null) throw new ArgumentNullException(nameof(query));");
            sb.AppendLine();

            if (registrations.Length > 0)
            {
                sb.AppendLine("switch (query)");
                sb.OpenBrace();
                foreach (var reg in registrations)
                {
                    sb.AppendLine($"case {reg.MessageFullyQualifiedName} typed:");
                    sb.Indent();
                    sb.AppendLine($"return (IAsyncEnumerable<TResult>)CreateStream<{reg.MessageFullyQualifiedName}, {reg.ResultFullyQualifiedName}>(typed, cancellationToken);");
                    sb.Unindent();
                }
                sb.AppendLine("default:");
                sb.Indent();
                sb.AppendLine("throw new InvalidOperationException($\"No handler registered for stream query type {query.GetType().FullName}. Ensure the handler is in the same compilation where [assembly: CortexMediatorGeneration] is applied.\");");
                sb.Unindent();
                sb.CloseBrace();
            }
            else
            {
                sb.AppendLine("throw new InvalidOperationException($\"No handler registered for stream query type {query.GetType().FullName}. Ensure the handler is in the same compilation where [assembly: CortexMediatorGeneration] is applied.\");");
            }

            sb.CloseBrace();
        }

        private static void EmitPipelineWrapperClasses(SourceTextBuilder sb)
        {
            // PipelineBehaviorNextDelegate<TCommand, TResult>
            sb.AppendLine("private sealed class PipelineBehaviorNextDelegate<TCommand, TResult> : ICommandHandler<TCommand, TResult>");
            sb.AppendLine("    where TCommand : ICommand<TResult>");
            sb.OpenBrace();
            sb.AppendLine("private readonly ICommandPipelineBehavior<TCommand, TResult> _behavior;");
            sb.AppendLine("private readonly ICommandHandler<TCommand, TResult> _next;");
            sb.AppendLine();
            sb.AppendLine("public PipelineBehaviorNextDelegate(ICommandPipelineBehavior<TCommand, TResult> behavior, ICommandHandler<TCommand, TResult> next)");
            sb.OpenBrace();
            sb.AppendLine("_behavior = behavior;");
            sb.AppendLine("_next = next;");
            sb.CloseBrace();
            sb.AppendLine();
            sb.AppendLine("public Task<TResult> Handle(TCommand command, CancellationToken cancellationToken)");
            sb.OpenBrace();
            sb.AppendLine("return _behavior.Handle(command, () => _next.Handle(command, cancellationToken), cancellationToken);");
            sb.CloseBrace();
            sb.CloseBrace();

            sb.AppendLine();

            // VoidPipelineBehaviorNextDelegate<TCommand>
            sb.AppendLine("private sealed class VoidPipelineBehaviorNextDelegate<TCommand> : ICommandHandler<TCommand>");
            sb.AppendLine("    where TCommand : ICommand");
            sb.OpenBrace();
            sb.AppendLine("private readonly ICommandPipelineBehavior<TCommand> _behavior;");
            sb.AppendLine("private readonly ICommandHandler<TCommand> _next;");
            sb.AppendLine();
            sb.AppendLine("public VoidPipelineBehaviorNextDelegate(ICommandPipelineBehavior<TCommand> behavior, ICommandHandler<TCommand> next)");
            sb.OpenBrace();
            sb.AppendLine("_behavior = behavior;");
            sb.AppendLine("_next = next;");
            sb.CloseBrace();
            sb.AppendLine();
            sb.AppendLine("public Task Handle(TCommand command, CancellationToken cancellationToken)");
            sb.OpenBrace();
            sb.AppendLine("return _behavior.Handle(command, () => _next.Handle(command, cancellationToken), cancellationToken);");
            sb.CloseBrace();
            sb.CloseBrace();

            sb.AppendLine();

            // QueryPipelineBehaviorNextDelegate<TQuery, TResult>
            sb.AppendLine("private sealed class QueryPipelineBehaviorNextDelegate<TQuery, TResult> : IQueryHandler<TQuery, TResult>");
            sb.AppendLine("    where TQuery : IQuery<TResult>");
            sb.OpenBrace();
            sb.AppendLine("private readonly IQueryPipelineBehavior<TQuery, TResult> _behavior;");
            sb.AppendLine("private readonly IQueryHandler<TQuery, TResult> _next;");
            sb.AppendLine();
            sb.AppendLine("public QueryPipelineBehaviorNextDelegate(IQueryPipelineBehavior<TQuery, TResult> behavior, IQueryHandler<TQuery, TResult> next)");
            sb.OpenBrace();
            sb.AppendLine("_behavior = behavior;");
            sb.AppendLine("_next = next;");
            sb.CloseBrace();
            sb.AppendLine();
            sb.AppendLine("public Task<TResult> Handle(TQuery query, CancellationToken cancellationToken)");
            sb.OpenBrace();
            sb.AppendLine("return _behavior.Handle(query, () => _next.Handle(query, cancellationToken), cancellationToken);");
            sb.CloseBrace();
            sb.CloseBrace();
        }
    }
}
